server:
  #端口号
  port: 7000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: gateway-server-1
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: lb://PROVIDE-1
        predicates:
        - Path=/provide/**
logging:
  level:
    org.springframework.cloud.gateway: debug