server:
  #端口号
  port: 8011
spring:
  application:
    name: provide-1
  cloud:
      sentinel:
        transport:
          port: 8720
          dashboard: localhost:8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
